version: '3'

services:
  yacw-frontend:
    image: laoliu233/yacw-frontend:latest
    restart: unless-stopped
    ports:
      - 80:80
  yacw-backend:
    image: laoliu233/yacw-backend:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SALT: [SALT]      # 用于加密密码的盐
      API_PATH: [PATH]  # 后端 API 的前缀，如 /api。用于部署
